<?php
use Egc\Auth\Identity;

$is_auth = Identity::isAuthenticated();
?>
<?php if(!$is_auth): ?>
<div id="loginBtns">
    <a href="#" class="show_hideReg"><img src="/img/registerHere.png" alt="Register" /></a>
    <a href="#;" class="show_hide"><img src="/img/login.png" alt="Login" /></a>
</div>
<script type="text/javascript">
    $('#loginBtns .show_hide').click(function(){
	$('#RegForm').slideUp();
	$('#loginForm').slideToggle();
    });
    $('#loginBtns .show_hideReg').click(function(){
	$('#loginForm').slideUp();
	$('#RegForm').slideToggle();
    });
</script>
<?php else: ?>
<div id="userBtns">
    <a href="/user"><img src="/img/myaccount.png" alt="My Account" /></a>
    <a href="/followings"><img src="/img/myWeb.png" alt="My Web" /></a>
    <a href="/user/logout"><img src="/img/logout.png" alt="Logout" /></a>
</div>
<?php endif; ?>

   <!-- Registration Form -->

   <div id="RegForm" class="slidingDivReg">
	  <form method="post" action="" style="float: left; position: relative; top: -13px;">
	  <span style="background: none repeat scroll 0 0 lightgray; border-radius: 7px 0 15px; color: white; font-style: italic; font-weight: bold; padding: 1px 5px 3px; position: relative; right: 16px; top: -8px;">unimplemented</span>
	  <div id="inputs">
		  <input type="text" name="username" placeholder="Choose Username" disabled="disabled"/>
		  <input type="password" name="password"  placeholder="Choose Password" disabled="disabled"/>
		  <input type="password" name="passwordVerify"  placeholder="Repeat Password" disabled="disabled"/>
		  <input type="text" name="email" placeholder="Enter Email" />
	  </div>

	  <input type="submit" name="register"  value="" disabled="disabled"/>
	 </form>
   </div>

   <!-- end of RegForm -->

   <!-- Login Form -->

   <div id="loginForm" class="slidingDiv">

	  <form method="post" action="/user/login" >
	  <div id="inputs">
		<span id="sprytextfield1">
			<input type="text" name="username" placeholder="Username..." />
			<span class="textfieldRequiredMsg">!</span>
		</span>
		<span id="sprytextfield2">
	  <input type="password" id="password" name="password" placeholder="Password..." />
	  <span class="textfieldRequiredMsg">!</span></span>
	  </div><!--end of inputs -->

	  <input type="submit" name="login"  value=""/>
	  </form>
   </div>

   <!-- end of loginForm -->
