<form action="/followings/save" method="post" name="user_profile">
	<fieldset>
		<legend>Please enter names of person/thing to follow</legend>
		<?php for ($id = 0; $id < $this->followings_max_count; $id++): ?>
		<?php
		if (isset($this->followings[$id]) &&
		    $this->followings[$id] instanceof Application\Model\Following)
		{
		    $following = $this->followings[$id];
		} else {
		    $following = new Application\Model\Following();
		}
		?>
		<fieldset>
			<label><span>Follow</span>
			<input type="text"
				name="followings[<?= $id ?>][followingName]"
				placeholder="Type name here" autocomplete="off" class="form-control"
				data-provide="typeahead" value="<?= $following->getFollowingName() ?>"></label>
			<input type="hidden" name="followings[<?= $id ?>][followingId]"
				value="<?= $following->getFollowingId() ?>">
			<input type="hidden" name="followings[<?= $id ?>][id]"
				value="<?= $following->getId() ?>">
			<input type="hidden" name="followings[<?= $id ?>][userId]"
				value="<?= $following->getUserId() ?>">
		</fieldset>
		<?php endfor; ?>
	</fieldset>
	<button type="submit" name="submit" class="btn btn-primary" value="">Save</button>
</form>
<script type="text/javascript">

jQuery(function() {
    var users = new Bloodhound({
        datumTokenizer: function (datum) {
            return Bloodhound.tokenizers.whitespace(datum.display_name);
        },
        queryTokenizer: Bloodhound.tokenizers.whitespace,
        limit: 10,
        remote: {
            url: '/twitter/users?q=%QUERY',
            filter: function (response) {
                return $.map(response.items, function (item) {
                    return {
                        id: item.id,
                        screen_name: item.screen_name,
                        name: item.name,
                        profile_image_url: item.profile_image_url
                    };
                });
            }
        }
    });

    users.initialize();

    $('[data-provide=typeahead]').typeahead({
        	minLength: 3,
            highlight: true,
            hint:true
        }, {
        name: 'tweeter-users',
        displayKey: 'screen_name',
        source: users.ttAdapter(),
        templates: {
        	empty: [
            	'<div style="padding:5px;color: red;" >',
            	'Unable find any user that match the current query.',
            	'</div>'
        	].join('\n'),
        	suggestion: Handlebars.compile(
                ['<div class="typeahead-item typeahead-account-item js-selectable" style="overflow: hidden;">',
                '<p class="js-nav has-social-context" role="option">',
                  '<img class="profile-img size32" src="{{profile_image_url}}">',
                  '<span class="typeahead-user-item-info">',
                      '<p class="fullname">{{name}}</p>',
                      '<p class="username">@<b>{{screen_name}}</b></p>',
                  '</span>',
                '</p>',
            '</div>'].join(''))
    	},
    }).on('typeahead:selected', function (obj, datum) {
        var following_name_element_name = obj.target.name,
        following_fieldset_group_name = following_name_element_name.match(/followings\[\d+\]/),
        following_id_element_name = following_fieldset_group_name+"[followingId]",
        following_id_element = $('[name="'+following_id_element_name+'"]')[0]
        if (following_id_element)
            following_id_element.value = datum.id;
    });;
});
</script>
