<!-- Feeds -->
<div id="feeds">

<?php
/* @var $following EgcTweet\Entity\Following */
foreach($this->followings as $key => $following):
?>

<div id="twitter-feed-<?= $key ?>"></div>
<script type="text/javascript">
jQuery(function() {
	var el = $('#twitter-feed-<?= $key ?>');
	<?php $obj_name = "t_{$key}";?>
	var <?= $obj_name?> = new EgcTweetSpinner(
		'/twitter/timeline/data/<?= $following->getFollowingId() ?>.json', {
			twitterprofile: '<?= $following->getFollowingName() ?>',
			element: $(el)
		}
	);
	<?= $obj_name?>.load();
});
</script>
<?php endforeach;?>
</div>
<!-- end of Feeds -->
